import type { Metadata } from "next";
import type { Locale } from "@/i18n/routing";
import { buildMetadata } from "@/lib/seo";
import { PageIntro } from "@/components/content/PageIntro";
import { Container } from "@/components/ui/Container";

const data = { ar: { title: "مسار تحصيل منظم من التقييم إلى الإغلاق", desc: "ثماني مراحل واضحة تحافظ على جودة الملف وتوازن بين الاسترداد والعلاقة التجارية.", steps: [["تقييم الملف", "فحص أساس المطالبة والمستندات والأطراف."], ["التحقق من المدين", "مراجعة بيانات الطرف ووضعه وقنوات التواصل المناسبة."], ["التواصل الأولي", "عرض المطالبة بوضوح ومهنية وتوثيق الاستجابة."], ["التذكير والمتابعة", "متابعة زمنية منظمة دون إرباك العلاقة التجارية."], ["التفاوض والتسوية", "اختبار حلول ودية قابلة للتطبيق ومتوازنة."], ["خطة السداد والإنذار النهائي", "تثبيت الالتزام أو إنهاء المرحلة الودية بوضوح."], ["الإحالة القانونية", "التنسيق مع محامين مرخصين عندما يصبح التصعيد ضروريًا."], ["التنفيذ والإغلاق", "متابعة الحكم أو السداد وإغلاق الملف بتقرير نهائي."]] }, en: { title: "A structured recovery path from assessment to closure", desc: "Eight clear stages protect file quality while balancing recovery and the commercial relationship.", steps: [["Case assessment", "Reviewing the claim basis, documents, and parties."], ["Debtor verification", "Checking counterparty details, status, and viable contact routes."], ["Initial engagement", "Presenting the claim clearly and documenting the response."], ["Reminders and follow-up", "A disciplined cadence that respects the commercial relationship."], ["Negotiation and settlement", "Testing practical, balanced amicable solutions."], ["Payment plan and final notice", "Formalizing commitment or closing the amicable stage clearly."], ["Legal referral", "Coordinating with licensed lawyers when escalation is necessary."], ["Enforcement and closure", "Following payment or judgment enforcement and issuing a final report."]] } } as const;
export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }): Promise<Metadata> { const { locale } = await params; return buildMetadata({ locale, path: "/how-we-work", title: `${data[locale].title} | RAM`, description: data[locale].desc }); }
export default async function HowWeWork({ params }: { params: Promise<{ locale: Locale }> }) { const { locale } = await params; const t = data[locale]; return <><PageIntro eyebrow={locale === "ar" ? "منهجية رام" : "THE RAM METHOD"} title={t.title} description={t.desc} /><section className="py-20"><Container><ol className="grid gap-5 lg:grid-cols-2">{t.steps.map(([title, text], i) => <li key={title} className="grid grid-cols-[4rem_1fr] gap-5 rounded-3xl border bg-surface p-6 shadow-elevated"><span className="text-3xl font-bold text-gold-500">{String(i + 1).padStart(2, "0")}</span><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 text-muted">{text}</p></div></li>)}</ol></Container></section></>; }
