import type { Metadata } from "next";
import type { Locale } from "@/i18n/routing";
import { buildMetadata, localizedUrl } from "@/lib/seo";
import { JsonLd } from "@/components/seo/JsonLd";
import { PageIntro } from "@/components/content/PageIntro";
import { InformationGrid, PageCTA, SplitNarrative } from "@/components/content/PageSections";
import { Container } from "@/components/ui/Container";

const data = {
  ar: { title: "مسار تحصيل منظم من التقييم إلى الإغلاق", desc: "ثماني مراحل واضحة تحافظ على جودة الملف وتوازن بين الاسترداد والعلاقة التجارية.", steps: [["تقييم الملف", "فحص أساس المطالبة والمستندات والأطراف والرصيد."], ["التحقق من المدين", "مراجعة بيانات الطرف ووضعه وقنوات التواصل المناسبة."], ["التواصل الأولي", "عرض المطالبة بوضوح ومهنية وتوثيق الاستجابة."], ["التذكير والمتابعة", "وتيرة زمنية منظمة دون إرباك العلاقة التجارية."], ["التفاوض والتسوية", "اختبار حلول ودية قابلة للتطبيق ومتوازنة."], ["خطة السداد والإنذار النهائي", "تثبيت الالتزام أو إنهاء المرحلة الودية بوضوح."], ["الإحالة القانونية", "التنسيق مع محامين مرخصين عندما يصبح التصعيد ضروريًا."], ["التنفيذ والإغلاق", "متابعة السداد أو الحكم وإصدار تقرير ختامي."]], principlesTitle: "كيف نقرر الخطوة التالية؟", principles: ["نقيس التقدم بالدفع والمعلومة والالتزام، لا بعدد الاتصالات.", "نرفع الاعتراضات والعروض للقرار بدل تركها معلقة.", "نستخدم الإجراء القانوني عندما يلائم الملف وبعد مراجعة مختصة.", "لا نضمن نتيجة أو مدة؛ نوضح العوامل والمخاطر ونقاط القرار."], reportsTitle: "ما الذي يظهر في تقرير المتابعة؟", reports: [["الحالة الحالية", "أين وصل الملف وما آخر تطور موثق."], ["الرصيد والدفعات", "المبلغ القائم وأي دفعة أو تسوية مثبتة."], ["الاعتراضات والمخاطر", "ما يمنع التقدم وما يحتاج مستندًا أو رأيًا."], ["الخطوة والقرار", "الإجراء التالي والموعد وما يحتاج موافقة العميل."]]},
  en: { title: "A structured recovery path from assessment to closure", desc: "Eight clear stages protect matter quality while balancing recovery and the commercial relationship.", steps: [["Matter assessment", "Review claim basis, records, parties, and balance."], ["Debtor verification", "Check counterparty details, status, and contact routes."], ["Initial engagement", "Present the claim clearly and document the response."], ["Reminders and follow-up", "Use a disciplined cadence that respects the relationship."], ["Negotiation and settlement", "Test practical, balanced amicable solutions."], ["Payment plan and final notice", "Formalize commitment or close the amicable stage."], ["Legal referral", "Coordinate with licensed lawyers when escalation is necessary."], ["Enforcement and closure", "Follow payment or judgment and issue a closure report."]], principlesTitle: "How do we decide the next step?", principles: ["Measure progress through payment, information, and commitment—not call counts.", "Raise disputes and offers for decisions rather than leaving them pending.", "Use legal action when suitable and after specialist review.", "Do not promise outcome or timing; explain factors, risks, and decisions."], reportsTitle: "What does a follow-up report show?", reports: [["Current status", "Where the matter stands and the latest documented development."], ["Balance and payments", "Outstanding value and any verified payment or settlement."], ["Disputes and risks", "What blocks progress and what needs evidence or advice."], ["Next action and decision", "The next step, timing, and client approval required."]]},
} as const;

export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }): Promise<Metadata> { const { locale } = await params; return buildMetadata({ locale, path: "/how-we-work", title: `${data[locale].title} | RAM`, description: data[locale].desc }); }

export default async function HowWeWork({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params; const t = data[locale]; const ar = locale === "ar";
  const howTo = { "@context": "https://schema.org", "@type": "HowTo", name: t.title, description: t.desc, url: localizedUrl(locale, "/how-we-work"), inLanguage: locale, step: t.steps.map(([name, text], index) => ({ "@type": "HowToStep", position: index + 1, name, text })) };
  return <><JsonLd data={howTo} /><PageIntro eyebrow={ar ? "منهجية رام" : "THE RAM METHOD"} title={t.title} description={t.desc} /><section className="py-20"><Container><ol className="grid gap-5 lg:grid-cols-2">{t.steps.map(([title, text], i) => <li key={title} className="grid grid-cols-[4rem_1fr] gap-5 rounded-3xl border bg-surface p-6 shadow-elevated"><span className="text-3xl font-bold text-gold-500">{String(i + 1).padStart(2, "0")}</span><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 leading-7 text-muted">{text}</p></div></li>)}</ol></Container></section><SplitNarrative eyebrow={ar ? "منطق القرار" : "DECISION LOGIC"} title={t.principlesTitle} paragraphs={[ar ? "تتحرك الملفات الجيدة بإيقاع معروف: هدف لكل مرحلة، ومعلومة أو التزام متوقع، وموعد لاتخاذ القرار إذا لم يتحقق." : "Well-managed matters move to a known rhythm: an objective for each stage, an expected fact or commitment, and a date for deciding what follows."]} points={[...t.principles]} /><InformationGrid eyebrow={ar ? "شفافية المتابعة" : "REPORTING CLARITY"} title={t.reportsTitle} items={t.reports.map(([title, text]) => ({ title, text }))} tone="soft" /><PageCTA title={ar ? "حوّل المطالبة إلى ملف له مسار وقرار" : "Turn the claim into a matter with a route and decisions"} text={ar ? "ابدأ بملخص واضح، وسنحدد المستندات اللازمة للتقييم الأولي." : "Start with a clear summary and we will identify the records needed for initial assessment."} action={ar ? "ابدأ التقييم" : "Start the assessment"} secondary={ar ? "جهّز ملفك" : "Prepare your file"} secondaryHref="/insights/prepare-debt-file" /></>;
}
