import type { ContentBlock, EntryType, LocalizedEntry, Locale } from "@/lib/content/schema";

type L = { ar: string; en: string };
type Detail = { title: L; text: L };
type QA = { question: L; answer: L };
type Definition = {
  slug: string;
  title: L;
  excerpt: L;
  overview: L[];
  focus: Detail[];
  callout: L;
  faqs: QA[];
};

const publishedAt = "2026-09-15T00:00:00.000Z";
const l = (ar: string, en: string): L => ({ ar, en });
const d = (arTitle: string, arText: string, enTitle: string, enText: string): Detail => ({ title: l(arTitle, enTitle), text: l(arText, enText) });
const q = (arQuestion: string, arAnswer: string, enQuestion: string, enAnswer: string): QA => ({ question: l(arQuestion, enQuestion), answer: l(arAnswer, enAnswer) });

const serviceProcess: Detail[] = [
  d("التقييم والتحقق", "نراجع أساس المطالبة والأطراف والرصيد والمستندات ونحدد نقاط القوة والنقص.", "Assessment and verification", "We review the claim basis, parties, balance, and records, identifying strengths and gaps."),
  d("بناء الاستراتيجية", "نختار القنوات والتوقيت والصلاحيات ومسار التصعيد بحسب هدف العميل وطبيعة المدين.", "Strategy design", "We select channels, timing, authority, and escalation according to the client's objective and debtor profile."),
  d("التواصل الموثق", "نقدم المطالبة بوضوح ومهنية ونسجل الردود والاعتراضات والوعود دون ضغط غير مشروع.", "Documented engagement", "We present the claim clearly and professionally, recording responses, disputes, and commitments without unlawful pressure."),
  d("التفاوض والمتابعة", "نختبر السداد الكامل أو التسوية أو خطة دفع قابلة للقياس ضمن الصلاحيات المتفق عليها.", "Negotiation and follow-up", "We test full payment, settlement, or a measurable payment plan within agreed authority."),
  d("التصعيد والإغلاق", "عند الحاجة ننسق الإحالة إلى مختصين مرخصين، ثم نوثق السداد أو النتيجة في تقرير ختامي.", "Escalation and closure", "Where required, we coordinate referral to licensed specialists and document payment or outcome in a closure report."),
];

const serviceEssentials: Detail[] = [
  d("ملخص المطالبة", "الأطراف والمبلغ والعملة وتاريخ الاستحقاق والهدف من التكليف.", "Claim summary", "Parties, value, currency, due date, and engagement objective."),
  d("أساس الدين", "العقد أو أمر الشراء أو العرض المقبول وأي ملاحق أو تعديلات.", "Debt basis", "Contract, purchase order, accepted quote, and relevant amendments."),
  d("إثبات الأداء", "الفواتير والتسليم أو قبول الخدمة وكشف الحساب والدفعات السابقة.", "Performance evidence", "Invoices, delivery or service acceptance, account statement, and prior payments."),
  d("سجل التواصل", "الإقرارات والاعتراضات والوعود السابقة وأسماء أصحاب القرار المعروفين.", "Communication record", "Acknowledgements, objections, promises, and known decision owners."),
];

const industryProcess: Detail[] = [
  d("فهم دورة القطاع", "نحدد كيف ينشأ الالتزام ومن يعتمد الفاتورة وما المستند الذي يثبت الأداء.", "Understand the sector cycle", "We identify how the obligation arises, who approves payment, and which record proves performance."),
  d("تصنيف الملفات", "نقسم المطالبات بحسب القيمة والعمر والمخاطر والعلاقة وقابلية التحصيل.", "Segment matters", "We group claims by value, age, risk, relationship, and recoverability."),
  d("تخصيص التواصل", "نضبط الرسالة والقناة والتكرار مع حساسية القطاع والبيانات.", "Tailor engagement", "We adapt message, channel, and cadence to sector and data sensitivity."),
  d("إدارة الاستثناءات", "نرفع النزاعات والحالات الحساسة والعروض التي تحتاج قرارًا بدل إبقائها في قائمة المتابعة.", "Manage exceptions", "We escalate disputes, sensitive cases, and offers requiring decisions rather than leaving them in a queue."),
  d("التقرير والتحسين", "نوضح الحالة والخطوة التالية وأسباب التعثر ليستفيد العميل من كل ملف.", "Report and improve", "We show status, next step, and delay reasons so each matter improves future practice."),
];

const industryEssentials: Detail[] = [
  d("بيانات موحدة", "رصيد وتاريخ استحقاق وحالة وجهة اتصال واضحة لكل مطالبة.", "Consistent data", "Clear balance, due date, status, and contact for each claim."),
  d("مصفوفة صلاحيات", "من يعتمد العرض أو خطة السداد أو الإحالة أو الإغلاق.", "Authority matrix", "Who approves offers, payment plans, referrals, and closure."),
  d("ضوابط الخصوصية", "تحديد الحد الأدنى من البيانات وقنوات المشاركة والأشخاص المخولين.", "Privacy controls", "Define minimum data, sharing channels, and authorized people."),
  d("تعريف التقرير", "حالات موحدة وتكرار مناسب ونقاط قرار قابلة للمراجعة.", "Reporting definition", "Consistent statuses, suitable cadence, and reviewable decisions."),
];

const articleProcess: Detail[] = [
  d("حدد الوقائع", "اكتب الأطراف والرصيد والتواريخ والاعتراضات دون استنتاجات غير موثقة.", "Establish the facts", "Record parties, balance, dates, and disputes without unsupported assumptions."),
  d("رتب الأدلة", "اربط كل نقطة بعقد أو فاتورة أو تسليم أو مراسلة قابلة للمراجعة.", "Organize evidence", "Connect each point to a reviewable contract, invoice, delivery record, or message."),
  d("اختر هدف المرحلة", "حدد هل المطلوب معلومات أو دفع أو تسوية أو قرار إحالة.", "Set the stage objective", "Decide whether the next goal is information, payment, settlement, or referral."),
  d("ضع موعد قرار", "لا تترك المتابعة أو التفاوض مفتوحين دون تاريخ ومالك واضح.", "Set a decision date", "Do not leave follow-up or negotiation open-ended without a date and owner."),
  d("وثق النتيجة", "سجل ما تحقق وما تعطل والخطوة التالية حتى لا يعود الملف إلى نقطة الصفر.", "Document the outcome", "Record progress, blockers, and next action so the matter does not restart from zero."),
];

const articleEssentials: Detail[] = [
  d("لا تضمن النتيجة", "التحصيل يتأثر بالمستندات والملاءة والوقت والاختصاص واستجابة الطرف الآخر.", "Do not promise outcomes", "Recovery depends on evidence, solvency, timing, jurisdiction, and counterparty response."),
  d("افصل الحقيقة عن الافتراض", "استخدم السجل والمستند بدل الذاكرة أو الانطباع الشخصي.", "Separate fact from assumption", "Use records and evidence rather than memory or impressions."),
  d("حافظ على التناسب", "اختر خطوة تناسب قيمة المطالبة ومخاطرها والعلاقة التجارية.", "Keep action proportionate", "Choose a step suited to claim value, risk, and the commercial relationship."),
  d("اطلب مراجعة مختصة", "المسائل القانونية أو العابرة للحدود تحتاج مختصًا مرخصًا في الاختصاص المعني.", "Use specialist review", "Legal and cross-border questions require licensed specialists in the relevant jurisdiction."),
];

const services: Definition[] = [
  {
    slug: "commercial-debt-collection",
    title: l("تحصيل الديون التجارية", "Commercial debt collection"),
    excerpt: l("إدارة احترافية للمستحقات التجارية المتأخرة مع الحفاظ على العلاقة التجارية كلما أمكن.", "Professional recovery of overdue commercial receivables while preserving viable business relationships."),
    overview: [l("تحصيل الديون التجارية هو مسار منظم لاسترداد الفواتير والمبالغ التعاقدية المتأخرة من الشركات والجهات المهنية. يبدأ العمل بفهم أساس المطالبة وجودة مستنداتها، وليس بمجرد تكرار الاتصالات.", "Commercial debt collection is a structured route for recovering overdue invoices and contractual amounts from businesses. Work begins with the claim basis and document quality, not repetitive calling."), l("تتعامل رام مع كل ملف بحسب قيمته وعمره وطبيعة العلاقة واستجابة المدين، بهدف تحويل مطالبة مبعثرة إلى ملف قابل للمتابعة والقياس.", "RAM treats each matter according to value, age, relationship context, and debtor response, turning a fragmented claim into a trackable course of action.")],
    focus: [d("فواتير متأخرة", "مبالغ مستحقة عن سلع أو خدمات تم توريدها ولم تُسدد في موعدها.", "Overdue invoices", "Amounts due for delivered goods or completed services."), d("مستحقات تعاقدية", "مطالبات تستند إلى عقد أو أمر شراء أو اتفاق تجاري واضح.", "Contractual receivables", "Claims supported by a contract, purchase order, or clear agreement."), d("محافظ متعددة", "ترتيب عدة مدينين بحسب الأولوية وقابلية التحصيل.", "Multi-account portfolios", "Prioritizing several debtors by urgency and recoverability."), d("علاقات مستمرة", "تواصل حازم ومحترم يقلل الضرر غير الضروري على العلاقة.", "Ongoing relationships", "Firm, respectful engagement that avoids unnecessary relationship damage.")],
    callout: l("لا تضمن أي جهة مهنية نتيجة التحصيل. جودة المستندات والملاءة وعمر المطالبة وموقف المدين عوامل تؤثر في المسار والنتيجة.", "No professional provider can guarantee recovery. Records, solvency, claim age, and the debtor's position affect route and outcome."),
    faqs: [q("هل يمكن جمع عدة فواتير في ملف واحد؟", "نعم، إذا ربط كشف حساب مرتب كل فاتورة بتاريخها ومبلغها ودفعاتها.", "Can several invoices form one matter?", "Yes, where a reconciled statement links each invoice to its date, value, and payments."), q("هل التحصيل ينهي العلاقة التجارية؟", "ليس بالضرورة؛ يمكن ضبط النبرة وخيارات التسوية لحماية علاقة قابلة للاستمرار.", "Does collection end the relationship?", "Not necessarily; tone and settlement options can protect a viable relationship."), q("متى يناسب التصعيد القانوني؟", "بعد استنفاد الخيارات الودية أو ظهور نزاع أو خطر يستلزم مراجعة قانونية متخصصة.", "When is legal escalation suitable?", "After amicable routes are exhausted or a dispute or risk needs specialist legal review.")],
  },
  {
    slug: "amicable-settlements",
    title: l("التسويات الودية", "Amicable settlements"),
    excerpt: l("تفاوض منظم للوصول إلى حلول قابلة للتنفيذ قبل التصعيد القانوني.", "Structured negotiation designed to reach workable resolutions before legal escalation."),
    overview: [l("التسوية الودية ليست تنازلًا تلقائيًا عن الحق؛ إنها تفاوض مبني على قدرة المدين وموقف الدائن وقوة المستندات للوصول إلى اتفاق يمكن تنفيذه ومتابعته.", "An amicable settlement is not an automatic surrender of rights. It is a negotiation grounded in capacity, creditor position, and evidence, aiming for a workable agreement."), l("تفيد عندما يكون السداد الفوري غير واقعي أو العلاقة التجارية ذات قيمة أو كلفة النزاع غير متناسبة، مع ضرورة تحديد الصلاحيات والمدة مسبقًا.", "It can help where immediate payment is unrealistic, the relationship matters, or dispute cost is disproportionate, provided authority and timing are set in advance.")],
    focus: [d("سداد مقطوع", "مناقشة دفعة واحدة بشروط يوافق عليها الدائن.", "Lump-sum payment", "A single payment on creditor-approved terms."), d("خطط سداد", "دفعات وتواريخ واضحة يمكن مراقبتها.", "Payment plans", "Clear installments and dates that can be monitored."), d("معالجة الاعتراض", "فصل الخلاف الحقيقي عن المماطلة وطلب مستند محدد.", "Dispute handling", "Separating genuine disagreement from delay and requesting evidence."), d("حماية العلاقة", "اختيار لغة وحل يحفظان مساحة للتعاون المستقبلي.", "Relationship protection", "Choosing language and terms that preserve future cooperation.")],
    callout: l("الاتفاق الجيد هو الاتفاق القابل للتنفيذ والمتابعة، لا العرض الذي يبدو جذابًا على الورق فقط.", "A good settlement is one that can be performed and monitored, not merely attractive on paper."),
    faqs: [q("هل يمكن تعديل خطة السداد؟", "يمكن بموافقة الدائن وتوثيق التعديل، لكن التكرار قد يعني أن الخطة غير واقعية.", "Can a plan be amended?", "Yes, with creditor approval and documented changes, though repetition may show the plan is unrealistic."), q("هل التسوية مناسبة لكل ملف؟", "لا، خصوصًا عند وجود خطر عاجل أو غياب نية موثوقة للالتزام.", "Is settlement right for every matter?", "No, particularly where urgent risk exists or there is no credible intent to comply."), q("ما الذي يجعل الاتفاق واضحًا؟", "رصيد متفق عليه وتواريخ وطريقة دفع وآثار إخلال مصاغة بما يناسب الملف.", "What makes an agreement clear?", "An agreed balance, dates, payment method, and appropriately documented default consequences.")],
  },
  {
    slug: "legal-debt-recovery",
    title: l("التحصيل القانوني", "Legal debt recovery"),
    excerpt: l("تنسيق مسار المطالبة القانونية والتنفيذ عبر مختصين مرخصين عند تعذر الحل الودي.", "Coordinated legal recovery and enforcement through licensed specialists when amicable routes are exhausted."),
    overview: [l("التحصيل القانوني مرحلة مدروسة عندما لا تحقق المحاولات الودية نتيجة أو يحتاج النزاع إلى إجراء قضائي. يسبق الإحالة تقييم الإثبات والاختصاص والكلفة والجدوى.", "Legal recovery is a considered stage when amicable efforts fail or a dispute requires judicial action. Evidence, jurisdiction, cost, and viability are assessed before referral."), l("تنسق رام الملف التشغيلي والمستندي مع المحامين المرخصين، بينما تبقى الاستشارة والتمثيل والإجراءات القضائية لدى المهنيين المخولين.", "RAM coordinates operational and documentary work with licensed lawyers, while advice, representation, and court action remain with authorized professionals.")],
    focus: [d("تقييم قبل الإحالة", "كشف ثغرات الأدلة قبل تكبد كلفة الإجراء.", "Pre-referral assessment", "Identify evidence gaps before procedural cost."), d("تنظيم الملف", "تسلسل زمني واضح للعقود والفواتير والمراسلات.", "Matter organization", "A clear chronology of contracts, invoices, and messages."), d("تنسيق المحامين", "حزمة معلومات ونطاق عمل وقرارات عميل واضحة.", "Counsel coordination", "A clear information pack, scope, and client decisions."), d("التنفيذ والإغلاق", "متابعة ما بعد الحكم ضمن القانون وتقرير نهائي.", "Enforcement and closure", "Lawful post-judgment follow-up and a final report.")],
    callout: l("محتوى الموقع معلومات عامة وليس استشارة قانونية. يحدد المحامي المرخص الإجراء المناسب بعد مراجعة الوقائع والاختصاص.", "Website content is general information, not legal advice. Licensed counsel determines appropriate action after reviewing facts and jurisdiction."),
    faqs: [q("هل تبدأون بدعوى مباشرة؟", "عادة لا؛ يسبق الإحالة تقييم المستندات والخيارات والجدوى إلا إذا استلزم الملف مراجعة عاجلة.", "Do you file immediately?", "Usually not; records, options, and viability are assessed unless urgent review is required."), q("هل رام مكتب محاماة؟", "رام تنسق التحصيل والملف، وتبقى المشورة والتمثيل لدى محامين مرخصين.", "Is RAM a law firm?", "RAM coordinates recovery and the matter file; licensed lawyers provide advice and representation."), q("هل يمكن ضمان مدة القضية؟", "لا، فالمدة تتأثر بالمحكمة والتبليغ والاعتراضات والتنفيذ.", "Can litigation time be guaranteed?", "No. Court scheduling, service, objections, and enforcement affect timing.")],
  },
  {
    slug: "international-collections",
    title: l("التحصيل الدولي", "International collections"),
    excerpt: l("متابعة المطالبات العابرة للحدود عبر شبكة عمل إقليمية ودولية منظمة.", "Cross-border claim follow-up through a structured regional and international working network."),
    overview: [l("تضيف المطالبات الدولية اعتبارات الاختصاص واللغة والعملات والتبليغ. لذلك يبدأ الملف بتحديد الدول والأطراف والعقد ومكان الأداء أو الأصول المعروفة.", "International claims add jurisdiction, language, currency, and service considerations. Work starts by mapping countries, parties, contract, and known performance or asset locations."), l("تقدم رام نقطة تنسيق من مسقط وتعمل مع شركاء ومحامين مرخصين عند الحاجة، مع اختلاف المسار والكلفة والمدة من دولة إلى أخرى.", "RAM provides a Muscat coordination point and works with partners and licensed lawyers where needed; route, cost, and timing vary by country.")],
    focus: [d("مطالبات عابرة للحدود", "عقود أو فواتير ترتبط بأكثر من دولة.", "Cross-border claims", "Contracts or invoices connected to more than one country."), d("تنسيق متعدد اللغات", "تنظيم الرسائل والمستندات الأساسية لتقليل الالتباس.", "Multilingual coordination", "Organizing key messages and records to reduce ambiguity."), d("إحالات محلية", "ربط الملف بمختص في الدولة التي تتطلب إجراءً.", "Local referrals", "Connecting the matter with specialists where action is required."), d("متابعة الأحكام", "تقييم الاعتراف والتنفيذ مع المختصين والجهات المعنية.", "Judgment follow-up", "Assessing recognition and enforcement with specialists and authorities.")],
    callout: l("لا يُفترض تنفيذ عقد أو حكم في دولة أخرى تلقائيًا؛ يجب تقييم الاختصاص والمستندات والمتطلبات المحلية.", "A contract or judgment is not automatically enforceable in another country; jurisdiction, records, and local requirements must be assessed."),
    faqs: [q("هل تتعاملون مع كل الدول؟", "يمكن إجراء فحص أولي، ثم يتحدد القبول وفق الاختصاص والتغطية المحلية وطبيعة الملف.", "Do you cover every country?", "An initial screen is possible; acceptance depends on jurisdiction, local coverage, and matter type."), q("هل تكفي النسخ الإلكترونية؟", "تكفي غالبًا للتقييم الأولي، وقد تُطلب أصول أو ترجمات أو تصديقات لاحقًا.", "Are electronic copies sufficient?", "Usually for initial review; originals, translations, or certification may be needed later."), q("هل يمكن تنفيذ حكم أجنبي في عُمان؟", "قد يكون ممكنًا وفق شروط قانونية يراجعها محامٍ مرخص؛ الحكم لا ينفذ تلقائيًا.", "Can a foreign judgment be enforced in Oman?", "It may be possible subject to conditions reviewed by licensed counsel; enforcement is not automatic.")],
  },
  {
    slug: "field-collection",
    title: l("التحصيل الميداني", "Field collection"),
    excerpt: l("زيارات واتصالات ميدانية مدروسة لدعم التحقق والتواصل وتسريع التسوية.", "Planned field engagement supporting verification, communication, and faster resolution."),
    overview: [l("يضيف التحصيل الميداني قناة عملية عندما لا تكفي الاتصالات المكتبية أو يلزم التحقق من بيانات النشاط والعنوان. الزيارة خطوة مهنية لها هدف وسجل، وليست مواجهة.", "Field collection adds a practical channel when desk contact is insufficient or business and address details need verification. A visit is a professional step with a purpose and record, not confrontation."), l("يعمل الوكلاء ضمن تعليمات واضحة تراعي الخصوصية والاحترام والقانون، دون كشف معلومات المطالبة لأطراف غير معنية.", "Agents work under clear instructions respecting privacy, professional conduct, and law, without disclosing claim information to unrelated parties.")],
    focus: [d("التحقق من العنوان", "تأكيد الموقع أو النشاط عبر قنوات مشروعة.", "Address verification", "Confirming location or activity through legitimate channels."), d("تسليم إشعار", "إيصال مراسلة ضمن الأسلوب والنطاق المعتمدين.", "Notice delivery", "Delivering communication within the approved method and scope."), d("اجتماع مباشر", "فتح تفاوض مع ممثل مخول ومتعاون.", "Direct meeting", "Opening negotiation with an authorized, cooperative representative."), d("تقرير ميداني", "توثيق الوقت والنتيجة والمعلومات ذات الصلة.", "Field report", "Recording time, outcome, and relevant facts.")],
    callout: l("لا يُستخدم التهديد أو الإحراج أو كشف المطالبة للغير. كل زيارة يجب أن تكون مشروعة ومحترمة ومتناسبة مع الهدف.", "Threats, embarrassment, and disclosure to third parties are unacceptable. Every visit must be lawful, respectful, and proportionate."),
    faqs: [q("هل الزيارة مناسبة لكل ملف؟", "لا؛ تُستخدم فقط عندما تضيف قيمة بعد مراجعة الهدف والخصوصية والتكلفة.", "Is a visit right for every matter?", "No; it is used only when it adds value after reviewing purpose, privacy, and cost."), q("هل يتم تصوير الموقع؟", "أي توثيق مرئي يخضع للقانون والتعليمات والغرض المشروع ولا يتم تلقائيًا.", "Is the location photographed?", "Any visual record is subject to law, instructions, and legitimate purpose; it is not automatic."), q("ماذا بعد الزيارة؟", "يتلقى العميل تقريرًا بالنتيجة والخطوة المقترحة للمتابعة أو التفاوض.", "What follows a visit?", "The client receives an outcome report and a proposed follow-up or negotiation step.")],
  },
  {
    slug: "recovery-advisory",
    title: l("استشارات استرداد المستحقات", "Corporate recovery advisory"),
    excerpt: l("مراجعة سياسات الائتمان والتحصيل وبناء إجراءات تقلل التعثر وتحسن القرار.", "Reviewing credit and collection policies to reduce delinquency and improve recovery decisions."),
    overview: [l("تعالج استشارات الاسترداد ما يحدث قبل تأخر الفاتورة وبعده: شروط الائتمان وتوثيق التسليم وملكية المتابعة والتصعيد والتقارير.", "Recovery advisory addresses what happens before and after an invoice becomes overdue: credit terms, delivery evidence, ownership, escalation, and reporting."), l("السياسة الفعالة ليست الأكثر تشددًا؛ بل الأنسب لدورة المبيعات والقطاع، وتوضح من يفعل ماذا ومتى وبأي مستند.", "An effective policy is not simply the strictest; it fits the sales cycle and sector and defines who does what, when, and with which record.")],
    focus: [d("سياسة الائتمان", "فتح الحساب والحدود والموافقات والمراجعة.", "Credit policy", "Account opening, limits, approvals, and review."), d("دورة التحصيل", "توقيت واضح من قبل الاستحقاق حتى الإحالة.", "Collection cycle", "Clear timing from pre-due reminders through referral."), d("حوكمة المستندات", "ربط العقد والتسليم والفاتورة والمراسلات.", "Document governance", "Connecting contract, delivery, invoice, and correspondence."), d("تقارير الذمم", "رؤية العمر والتركيز والاعتراضات والوعود.", "Receivables reporting", "Visibility into aging, concentration, disputes, and promises.")],
    callout: l("أفضل وقت لتحسين التحصيل هو قبل أن تصبح الذمم قديمة؛ وضوح الشروط والمستندات والمسؤوليات يقوي أي مطالبة لاحقة.", "The best time to improve recovery is before receivables age; clear terms, records, and ownership strengthen later claims."),
    faqs: [q("هل تناسب الاستشارة الشركات الصغيرة؟", "نعم، ويمكن بناء دورة مبسطة بقوالب قليلة دون نظام معقد.", "Is advisory useful for small companies?", "Yes; a simple cycle with a few templates can work without a complex system."), q("هل تشمل تدريب الفريق؟", "يمكن أن تشمل جلسات تطبيقية للمالية والمبيعات والإدارة وفق النطاق.", "Can it include team training?", "The scope can include practical sessions for finance, sales, and management."), q("هل هي بديل عن التحصيل؟", "هي مكملة له؛ تحسن الملفات المستقبلية بينما تحتاج الذمم القائمة لخطة منفصلة.", "Does it replace collection?", "It complements collection by improving future files; existing receivables need a separate plan.")],
  },
];

const industries: Definition[] = [
  ["banks-financial-institutions", l("البنوك والمؤسسات المالية", "Banks and financial institutions"), l("إدارة ملفات مالية تتطلب توثيقًا دقيقًا ومسارات تصعيد محكومة وتقارير قابلة للمراجعة.", "Financial recovery requiring precise records, controlled escalation, and reviewable reporting."), l("تحتاج المحافظ المالية إلى دقة في البيانات وتوحيد في التواصل وقدرة على إدارة الحجم دون فقد أثر القرار.", "Financial portfolios need data precision, consistent engagement, and volume handling without losing decision traceability."), [d("تقسيم المحافظ", "شرائح حسب النوع والعمر والقيمة والاستجابة.", "Portfolio segmentation", "Groups by type, age, value, and response."), d("حالات التعثر", "متابعة تستند إلى سجل ومستندات واضحة.", "Default management", "Follow-up grounded in clear records."), d("حالات حساسة", "مسارات خاصة للاعتراضات والمخاطر.", "Sensitive cases", "Dedicated routes for disputes and risk."), d("تقارير حوكمة", "حالة واستثناء وقرار مطلوب لكل ملف.", "Governance reporting", "Status, exception, and required decision per matter.")]],
  ["smes", l("الشركات الصغيرة والمتوسطة", "Small and medium enterprises"), l("حلول عملية لحماية التدفق النقدي دون استنزاف فرق العمل الداخلية.", "Practical recovery support that protects cash flow without draining internal teams."), l("قد تؤثر فاتورة واحدة متأخرة في سيولة الشركة الصغيرة. تساعد رام على فصل المتابعة عن عمل المؤسس والمبيعات وترتيب قرار مبكر.", "One overdue invoice can materially affect SME liquidity. RAM separates follow-up from founders and sales and supports earlier decisions."), [d("فواتير العملاء", "توريد وخدمات ومقاولات صغيرة.", "Customer invoices", "Supply, service, and contracting receivables."), d("حماية السيولة", "ترتيب الأولوية بحسب الأثر وقابلية الاسترداد.", "Cash-flow protection", "Priority by impact and recoverability."), d("وقت الإدارة", "نقل المتابعة المنظمة بعيدًا عن التشغيل اليومي.", "Management time", "Move disciplined follow-up away from daily operations."), d("تحسين الملفات", "كشف الثغرات التي تضعف المطالبات المقبلة.", "Better files", "Identify gaps that weaken future claims.")]],
  ["corporate-groups", l("المجموعات والشركات الكبرى", "Corporate groups"), l("إدارة محافظ متعددة الأطراف مع تقارير واضحة وأولويات قابلة للقياس.", "Multi-party portfolio handling with clear reporting and measurable priorities."), l("تحتاج المجموعات إلى حوكمة مشتركة بين المالية والقانونية والمبيعات عند تعدد الكيانات والفروع والعملات وأصحاب القرار.", "Corporate groups need shared governance across finance, legal, and sales when entities, branches, currencies, and decision owners differ."), [d("محافظ كبيرة", "فرز حسب القيمة والعمر والمخاطر.", "Large portfolios", "Segment by value, age, and risk."), d("كيانات متعددة", "تحديد الدائن الصحيح لكل ملف.", "Multiple entities", "Identify the correct creditor for each matter."), d("تقارير إدارية", "اتجاهات واستثناءات وقرارات بدل سجل اتصالات.", "Executive reporting", "Trends, exceptions, and decisions rather than call logs."), d("تصعيد واضح", "ربط المرحلة بمالك قرار ومدة.", "Clear escalation", "Connect each stage to an owner and timeframe.")]],
  ["law-firms-consultants", l("مكاتب المحاماة والاستشارات", "Law firms and consultants"), l("دعم تحصيلي وتشغيلي يكمل العمل القانوني والاستشاري دون خلط الأدوار.", "Operational recovery support that complements legal and advisory work without blurring roles."), l("تعمل رام كشريك تنفيذي للبحث والتواصل والمتابعة والتقارير، بينما تبقى المشورة القانونية والتمثيل لدى المحامي المرخص.", "RAM supports research, engagement, follow-up, and reporting while legal advice and representation remain with licensed counsel."), [d("تنفيذ ميداني", "زيارات وتحقق ضمن التعليمات والقانون.", "Field execution", "Visits and verification under instruction and law."), d("تفاوض تشغيلي", "حلول ضمن صلاحيات مكتوبة.", "Operational negotiation", "Solutions within written authority."), d("تنظيم الأدلة", "ملف وتسلسل زمني يسهلان المراجعة.", "Evidence organization", "A matter pack and chronology for review."), d("تقارير مهنية", "وقائع قابلة للاستخدام في القرار التالي.", "Professional reporting", "Facts usable in the next decision.")]],
  ["real-estate", l("العقارات وإدارة الأملاك", "Real estate and property management"), l("متابعة الإيجارات والرسوم والالتزامات المتأخرة ضمن سجل واضح.", "Follow-up of overdue rent, fees, and lease obligations with a clear record."), l("تجمع المطالبات العقارية العقد والإشغال والخدمات والتسليم وعدة رسوم، لذلك يجب تسوية الرصيد قبل بدء المتابعة.", "Property claims combine lease, occupancy, services, handover, and several charges, so the balance must be reconciled first."), [d("إيجارات متأخرة", "أرصدة مرتبطة بفترات عقد واضحة.", "Rental arrears", "Balances tied to clear lease periods."), d("رسوم خدمات", "مطالبات تحتاج أساس احتساب مفهومًا.", "Service charges", "Claims needing a clear calculation basis."), d("ما بعد الإخلاء", "أرصدة تعتمد على محضر التسليم والحالة.", "Post-vacating balances", "Balances relying on handover and condition."), d("محافظ وحدات", "تقسيم حسب العقار والوحدة والمرحلة.", "Unit portfolios", "Segment by property, unit, and stage.")]],
  ["healthcare", l("الرعاية الصحية", "Healthcare"), l("تحصيل حساس يراعي خصوصية البيانات وطبيعة العلاقة مع الأطراف.", "Sensitive recovery that respects data privacy and stakeholder relationships."), l("يجب فصل المعلومات المالية اللازمة عن البيانات الطبية الحساسة، والتركيز على الفاتورة والموافقة وجهة الدفع وسجل المطالبة.", "Necessary financial information must be separated from sensitive clinical data, focusing on invoice, authorization, payer, and claim history."), [d("فواتير خدمات", "رصيد مرتبط بخدمة وموافقة وجهة دفع.", "Service invoices", "Balance tied to a service, approval, and payer."), d("جهات ضامنة", "متابعة الرفض أو فرق الرصيد.", "Guarantor claims", "Follow-up of denials or balance differences."), d("خصوصية مشددة", "الحد الأدنى من البيانات اللازمة.", "Enhanced privacy", "Only the minimum necessary data."), d("تواصل حساس", "لغة تحمي الكرامة وتتجنب الضغط.", "Sensitive engagement", "Language that protects dignity and avoids pressure.")]],
  ["international-investors", l("المستثمرون والكيانات الدولية", "International investors and entities"), l("نقطة تنسيق محلية للمطالبات التجارية المرتبطة بعُمان والمنطقة.", "A local coordination point for commercial claims connected to Oman and the region."), l("يستفيد المستثمر الدولي من شريك محلي يفهم بيئة الأعمال واللغة وينظم الملف قبل التواصل أو الإحالة القانونية.", "International investors benefit from a local partner familiar with business context and language who organizes the matter before engagement or referral."), [d("نقطة اتصال محلية", "تنسيق موحد من مسقط.", "Local contact point", "Unified coordination from Muscat."), d("تواصل ثنائي اللغة", "تقليل الالتباس في الرسائل والمستندات.", "Bilingual engagement", "Reduce ambiguity in messages and records."), d("فهم السياق", "مراعاة العرف التجاري والهيكل المحلي.", "Context awareness", "Recognize commercial practice and local structure."), d("تنسيق الإحالات", "الربط بمختص مرخص عند الحاجة.", "Referral coordination", "Connect with licensed specialists when needed.")]],
].map(([slug, title, excerpt, overview, focus]) => ({
  slug: slug as string,
  title: title as L,
  excerpt: excerpt as L,
  overview: [overview as L, l("نكيّف البيانات والتواصل والتقارير مع طبيعة القطاع، مع إبقاء كل قرار متناسبًا مع وقائع الملف.", "We adapt data, engagement, and reporting to sector context while keeping each decision proportionate to matter facts.")],
  focus: focus as Detail[],
  callout: l("لا يعني فهم القطاع افتراض نتيجة موحدة؛ كل مطالبة تحتاج تقييم مستنداتها وأطرافها ومخاطرها بصورة مستقلة.", "Sector familiarity does not imply a standard outcome; each claim requires independent review of evidence, parties, and risk."),
  faqs: [q("هل تقبلون ملفًا واحدًا أم محفظة؟", "يمكن تقييم ملف منفرد أو محفظة، ويحدد النطاق بحسب البيانات والقيمة والجاهزية.", "Do you accept one matter or a portfolio?", "A single matter or portfolio can be assessed; scope depends on data, value, and readiness."), q("كيف تُحمى بيانات القطاع الحساسة؟", "نحدد الحد الأدنى من البيانات وقنوات المشاركة والصلاحيات في بداية التكليف.", "How is sensitive sector data protected?", "Minimum data, sharing channels, and access are defined at onboarding."), q("هل تتغير التقارير حسب القطاع؟", "نعم، يمكن تكييف الحالات والمؤشرات ونقاط القرار مع احتياجات فريق العميل.", "Does reporting vary by sector?", "Yes. Statuses, indicators, and decision points can fit the client team's needs.")],
}));

const articleSeeds: [string, L, L, L, Detail[]][] = [
  ["amicable-vs-legal-recovery", l("متى نختار التسوية الودية ومتى ننتقل للتحصيل القانوني؟", "Amicable or legal recovery: when to use each path"), l("إطار قرار يوازن بين السرعة وقوة الملف والعلاقة التجارية.", "A decision framework balancing speed, evidence, and the commercial relationship."), l("المساران الودي والقانوني قد يكونان مرحلتين في خطة واحدة. القرار الجيد يحدد ما يُجرب أولًا ومتى تنتهي مهلة التفاوض وما الذي يطلق الإحالة.", "Amicable and legal recovery may be stages in one plan. A sound decision defines what to try first, when negotiation ends, and what triggers referral."), [d("وضوح المسؤولية", "أساس الدين والاعتراضات المثبتة.", "Liability clarity", "Debt basis and supported disputes."), d("سلوك المدين", "الرد والدفعات أهم من الوعود.", "Debtor behavior", "Responses and payments matter more than promises."), d("قيمة العلاقة", "قد تبرر نافذة تفاوض محددة.", "Relationship value", "May justify a defined negotiation window."), d("خطر التأخير", "قد يفرض مراجعة عاجلة بدل الانتظار.", "Delay risk", "May require urgent review rather than waiting.")]],
  ["prepare-debt-file", l("كيف تجهّز ملف مطالبة قابلًا للتحصيل؟", "How to prepare a recoverable claim file"), l("قائمة للمستندات والسجلات التي تساعد على تقييم المطالبة.", "A checklist of records supporting sound claim assessment."), l("الملف الجيد يشرح من تعاقد مع من، وما تم توريده، ومتى استحق المبلغ، وما دُفع، وماذا قال الطرف الآخر دون حاجة إلى التخمين.", "A strong file explains who contracted, what was delivered, when payment fell due, what was paid, and what the counterparty said without guesswork."), [d("هوية الأطراف", "الأسماء القانونية والصفات والعناوين.", "Party identity", "Legal names, capacities, and addresses."), d("أساس الالتزام", "عقد أو طلب أو قبول واضح.", "Obligation basis", "Contract, order, or clear acceptance."), d("إثبات الأداء", "تسليم أو قبول أو إتمام خدمة.", "Performance evidence", "Delivery, acceptance, or service completion."), d("الرصيد", "فواتير ودفعات وإشعارات دائنة متطابقة.", "Balance", "Reconciled invoices, payments, and credits.")]],
  ["receivables-warning-signs", l("إشارات مبكرة لتعثّر الذمم المدينة", "Early warning signs in accounts receivable"), l("علامات تساعد فرق الإدارة على التدخل قبل تحول الفاتورة إلى نزاع.", "Signals helping teams act before an invoice becomes a dispute."), l("تظهر إشارات التعثر قبل الاستحقاق: تغير جهة الاتصال، وتأخر الموافقات، وتكرار طلب الفاتورة، ووعود دفع لا يتبعها تنفيذ.", "Warning signs appear before default: changing contacts, delayed approvals, repeated invoice requests, and payment promises without action."), [d("تغير التواصل", "غياب المسؤول المعتاد دون بديل.", "Contact changes", "The usual owner disappears without replacement."), d("وعود مكسورة", "تواريخ جديدة بلا دفعات.", "Broken promises", "New dates without payment."), d("اعتراض عام", "مشكلة مزعومة دون فاتورة أو بند.", "Vague dispute", "A claimed issue without invoice or item."), d("إعادة المستندات", "طلب متكرر لنسخ سبق إرسالها.", "Repeated records", "Repeated requests for previously sent documents.")]],
  ["debt-recovery-timeline-factors", l("ما الذي يحدد مدة تحصيل الدين؟", "What determines a debt recovery timeline?"), l("العوامل التي تسرّع الملف أو تؤخره دون وعود زمنية غير قابلة للضمان.", "Factors that accelerate or delay recovery without unsupported timing promises."), l("لا توجد مدة موحدة للتحصيل. ملف واضح ومدين متجاوب يختلف عن مطالبة قديمة أو متنازع عليها أو عابرة للحدود.", "There is no universal recovery timeline. A clear matter with a responsive debtor differs from an old, disputed, or cross-border claim."), [d("عمر الدين", "الزمن يزيد احتمال فقد المعلومات.", "Claim age", "Time increases the chance of information loss."), d("جودة المستند", "الملف المرتب يقلل زمن التحقق.", "Record quality", "An organized file reduces review time."), d("استجابة المدين", "رد محدد أسرع من الصمت.", "Debtor response", "A specific response moves faster than silence."), d("الاختصاص", "المحاكم والحدود تضيف إجراءات.", "Jurisdiction", "Courts and borders add procedure.")]],
  ["payment-plan-design", l("كيف تُبنى خطة سداد قابلة للتنفيذ؟", "How to design a workable payment plan"), l("عناصر تجعل خطة السداد قابلة للمتابعة بدل أن تكون تأجيلًا جديدًا.", "Elements that make a payment plan trackable rather than another delay."), l("الخطة الجيدة توازن بين قدرة المدين وحاجة الدائن إلى اليقين، وتحدد الرصيد والدفعة الأولى والتواريخ وطريقة الدفع وأثر الإخلال.", "A sound plan balances debtor capacity with creditor certainty and defines balance, first payment, dates, method, and default response."), [d("رصيد ثابت", "المبلغ الذي تغطيه الخطة.", "Fixed balance", "The amount covered by the plan."), d("دفعة أولى", "اختبار عملي للجدية والقدرة.", "Initial payment", "A practical test of intent and capacity."), d("تواريخ دقيقة", "لا عبارات مثل قريبًا أو لاحقًا.", "Exact dates", "No terms such as soon or later."), d("أثر الإخلال", "قرار واضح بعد فوات الاستحقاق.", "Default response", "A clear decision after a missed due date.")]],
  ["cross-border-claim-checklist", l("قائمة تجهيز مطالبة تجارية عابرة للحدود", "Cross-border commercial claim checklist"), l("ما يجب تحديده قبل إحالة مطالبة تشمل أكثر من دولة أو عملة.", "What to identify before referring a claim involving more than one country or currency."), l("المطالبة الدولية الجاهزة تحدد الدول والأطراف والعقد والعملة ومكان الأداء واللغة المتوقعة للمستندات.", "A ready international claim identifies countries, parties, contract, currency, performance location, and document languages."), [d("الدول", "مكان الأطراف والأداء والأصول المعروفة.", "Countries", "Party, performance, and known asset locations."), d("العقد", "القانون والاختصاص والتحكيم والإشعارات.", "Contract", "Law, jurisdiction, arbitration, and notice clauses."), d("العملة", "الفاتورة والدفع وأي تحويلات.", "Currency", "Invoice, payment, and conversions."), d("اللغة", "ما قد يحتاج ترجمة أو تصديقًا.", "Language", "What may need translation or certification.")]],
  ["invoice-dispute-or-nonpayment", l("نزاع فاتورة أم مجرد تأخر في السداد؟", "Invoice dispute or simple non-payment?"), l("تمييز الاعتراض الحقيقي عن المماطلة وبناء رد موثق.", "Distinguishing a genuine dispute from delay and building an evidence-based response."), l("النزاع الحقيقي يحدد بندًا أو كمية أو جودة أو تاريخًا. أما المماطلة فتكرر عبارات عامة دون تفاصيل أو مستندات.", "A genuine dispute identifies a term, quantity, quality issue, or date. Delay often repeats general statements without detail or evidence."), [d("اعتراض محدد", "واقعة قابلة للتحقق.", "Specific objection", "A verifiable fact."), d("مستند مقابل", "دليل يدعم موقف الطرف.", "Supporting record", "Evidence supporting the position."), d("رصيد غير مختلف", "جزء قد يبقى واجب الدفع.", "Undisputed balance", "A portion that may remain payable."), d("مالك قرار", "شخص مخول يحسم الاعتراض.", "Decision owner", "An authorized person who resolves the issue.")]],
  ["preserve-business-relationships", l("كيف تحصّل مستحقاتك وتحافظ على العلاقة التجارية؟", "How to recover receivables while preserving business relationships"), l("مبادئ تواصل تحمي السمعة دون إضعاف وضوح المطالبة.", "Communication principles that protect reputation without weakening claim clarity."), l("الحفاظ على العلاقة لا يعني تجنب الحديث عن الدين. رسالة مبكرة وواضحة ومحترمة أفضل من أشهر من الصمت ثم تصعيد مفاجئ.", "Preserving a relationship does not mean avoiding the debt conversation. Early, clear, respectful communication is better than silence followed by sudden escalation."), [d("نبرة محترمة", "وقائع وطلب دون اتهام.", "Respectful tone", "Facts and request without accusation."), d("رصيد واضح", "كشف مفهوم يقلل الالتباس.", "Clear balance", "An understandable statement reducing ambiguity."), d("قناة مناسبة", "التواصل مع الشخص المخول.", "Right channel", "Engage the authorized person."), d("خيارات واقعية", "حل يمكن قياسه وتنفيذه.", "Realistic options", "A solution that can be measured and performed.")]],
];

const articles: Definition[] = articleSeeds.map(([slug, title, excerpt, overview, focus]) => ({
  slug, title, excerpt,
  overview: [overview, l("يعرض هذا الدليل إطارًا عمليًا عامًا يساعد فرق المالية والإدارة على طرح الأسئلة الصحيحة، مع ضرورة تكييف القرار مع مستندات الملف والاختصاص.", "This guide provides a general framework for finance and management teams to ask the right questions; every decision still needs to fit the matter and jurisdiction.")],
  focus,
  callout: l("هذه المادة للتثقيف العام ولا تشكل استشارة قانونية أو ضمانًا لنتيجة التحصيل.", "This material is general education, not legal advice or a guarantee of recovery."),
  faqs: [q("هل تنطبق هذه الخطوات على كل مطالبة؟", "هي إطار بداية؛ يجب تكييفها مع العقد والمستندات والأطراف والدولة.", "Do these steps apply to every claim?", "They are a starting framework and must be adapted to contract, records, parties, and country."), q("متى أطلب مساعدة متخصصة؟", "عند ضعف المستندات أو وجود نزاع أو خطر أو أطراف في أكثر من دولة أو تعطل المتابعة الداخلية.", "When should I seek specialist support?", "When evidence is weak, a dispute or risk exists, parties span countries, or internal follow-up is stuck."), q("هل يمكن ضمان النتيجة بعد تجهيز الملف؟", "لا، لكن الملف المنظم يحسن جودة التقييم وسرعة القرار ويحافظ على الأدلة.", "Does preparation guarantee recovery?", "No, but an organized file improves assessment, decision speed, and evidence preservation.")],
}));

function blocks(definition: Definition, locale: Locale, type: EntryType): ContentBlock[] {
  const focusHeading = type === "service" ? l("ما تغطيه الخدمة", "What the service covers") : type === "industry" ? l("احتياجات هذا القطاع", "Needs in this sector") : l("الخلاصة العملية", "Practical takeaways");
  const essentialsHeading = type === "article" ? l("نقاط يجب الانتباه لها", "Points to keep in mind") : l("ما نحتاجه لتقييم منظم", "What supports a structured assessment");
  const process = type === "article" ? articleProcess : type === "industry" ? industryProcess : serviceProcess;
  const essentials = type === "article" ? articleEssentials : type === "industry" ? industryEssentials : serviceEssentials;
  return [
    { type: "rich_text", heading: locale === "ar" ? "نظرة عملية" : "A practical overview", paragraphs: definition.overview.map((item) => item[locale]) },
    { type: "features", heading: focusHeading[locale], items: definition.focus.map((item) => ({ title: item.title[locale], text: item.text[locale] })) },
    { type: "steps", heading: locale === "ar" ? "المسار خطوة بخطوة" : "Step-by-step approach", items: process.map((item) => ({ title: item.title[locale], text: item.text[locale] })) },
    { type: "features", heading: essentialsHeading[locale], items: essentials.map((item) => ({ title: item.title[locale], text: item.text[locale] })) },
    { type: "callout", heading: locale === "ar" ? "ملاحظة مهمة" : "Important note", text: definition.callout[locale] },
    { type: "faq", heading: locale === "ar" ? "أسئلة شائعة" : "Frequently asked questions", items: definition.faqs.map((item) => ({ question: item.question[locale], answer: item.answer[locale] })) },
  ];
}

function expand(type: EntryType, definitions: Definition[]): LocalizedEntry[] {
  return definitions.flatMap((definition, index) => (["ar", "en"] as Locale[]).map((locale) => ({
    id: `${type}-${index + 1}-${locale}`,
    type,
    locale,
    slug: definition.slug,
    title: definition.title[locale],
    excerpt: definition.excerpt[locale],
    eyebrow: type === "service" ? (locale === "ar" ? "خدمة متخصصة" : "Specialist service") : type === "industry" ? (locale === "ar" ? "خبرة قطاعية" : "Sector expertise") : (locale === "ar" ? "دليل عملي" : "Practical guide"),
    publishedAt,
    updatedAt: publishedAt,
    author: type === "article" ? (locale === "ar" ? "فريق رام الاستشاري" : "RAM Advisory Team") : undefined,
    category: type === "article" ? "debt-recovery" : undefined,
    blocks: blocks(definition, locale, type),
  })));
}

export const seedEntries: LocalizedEntry[] = [
  ...expand("service", services),
  ...expand("industry", industries),
  ...expand("article", articles),
];
