import Image from "next/image";
import { useLocale } from "next-intl";
import { Mail, MapPin, Phone } from "lucide-react";

import { Link } from "@/i18n/navigation";
import { Container } from "@/components/ui/Container";
import { LINKS, SITE } from "@/lib/site";

const copy = { ar: { intro: "شريك مهني في تحصيل الديون التجارية والتسويات والاسترداد القانوني والدولي من مسقط، سلطنة عُمان.", services: "الخدمات", company: "الشركة", resources: "المعرفة", rights: "جميع الحقوق محفوظة.", links: ["تحصيل الديون التجارية", "التسويات الودية", "التحصيل القانوني", "التحصيل الدولي"] }, en: { intro: "Professional commercial debt collection, settlements, legal and international recovery from Muscat, Sultanate of Oman.", services: "Services", company: "Company", resources: "Resources", rights: "All rights reserved.", links: ["Commercial collection", "Amicable settlements", "Legal recovery", "International collections"] } } as const;

export function Footer() { const locale = useLocale() === "en" ? "en" : "ar"; const t = copy[locale]; return <footer className="mesh-navy text-mist-100/75"><Container className="py-16"><div className="grid gap-12 md:grid-cols-2 xl:grid-cols-12"><div className="xl:col-span-4"><Image src="/brand/logo-footer.png" alt="RAM" width={240} height={70} className="h-14 w-auto brightness-0 invert" /><p className="mt-6 max-w-sm">{t.intro}</p></div><div className="xl:col-span-2"><h2 className="font-bold text-gold-300">{t.services}</h2><ul className="mt-5 space-y-3">{t.links.map((label, i) => <li key={label}><Link href={`/services/${["commercial-debt-collection", "amicable-settlements", "legal-debt-recovery", "international-collections"][i]}`}>{label}</Link></li>)}</ul></div><div className="xl:col-span-2"><h2 className="font-bold text-gold-300">{t.company}</h2><ul className="mt-5 space-y-3"><li><Link href="/about">{locale === "ar" ? "عن رام" : "About RAM"}</Link></li><li><Link href="/how-we-work">{locale === "ar" ? "منهجية العمل" : "How we work"}</Link></li><li><Link href="/compliance-and-confidentiality">{locale === "ar" ? "الامتثال والسرية" : "Compliance"}</Link></li><li><Link href="/contact">{locale === "ar" ? "التواصل" : "Contact"}</Link></li></ul></div><div className="xl:col-span-2"><h2 className="font-bold text-gold-300">{t.resources}</h2><ul className="mt-5 space-y-3"><li><Link href="/insights">{locale === "ar" ? "المقالات" : "Insights"}</Link></li><li><Link href="/faq">{locale === "ar" ? "الأسئلة الشائعة" : "FAQ"}</Link></li><li><Link href="/privacy">{locale === "ar" ? "الخصوصية" : "Privacy"}</Link></li><li><Link href="/terms">{locale === "ar" ? "الشروط" : "Terms"}</Link></li><li><Link href="/disclaimer">{locale === "ar" ? "إخلاء المسؤولية" : "Disclaimer"}</Link></li></ul></div><div className="xl:col-span-2"><h2 className="font-bold text-gold-300">{locale === "ar" ? "تواصل" : "Contact"}</h2><ul className="mt-5 space-y-4"><li><a href={LINKS.phone} className="flex gap-2" dir="ltr"><Phone className="size-4 text-gold-300" />{SITE.phoneDisplay}</a></li><li><a href={LINKS.email} className="flex gap-2" dir="ltr"><Mail className="size-4 text-gold-300" />{SITE.email}</a></li><li className="flex gap-2"><MapPin className="size-4 text-gold-300" />{locale === "ar" ? SITE.location.ar : SITE.location.en}</li></ul></div></div><div className="mt-14 flex flex-wrap justify-between gap-4 border-t border-white/10 pt-7 text-sm"><p>© {new Date().getFullYear()} RAM Sustainable Development. {t.rights}</p><a href={LINKS.companyProfile} target="_blank" rel="noreferrer" className="text-gold-300">{locale === "ar" ? "تحميل الملف التعريفي" : "Company profile"}</a></div></Container></footer>; }
