import type { Metadata } from "next";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import type { Locale } from "@/i18n/routing";
import { buildMetadata } from "@/lib/seo";
import { LINKS, SITE } from "@/lib/site";
import { PageIntro } from "@/components/content/PageIntro";
import { ContactForm } from "@/components/sections/ContactForm";
import { Container } from "@/components/ui/Container";
export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }): Promise<Metadata> { const { locale } = await params; const ar = locale === "ar"; return buildMetadata({ locale, path: "/contact", title: ar ? "تواصل مع رام لتحصيل الديون" : "Contact RAM Debt Recovery", description: ar ? "اطلب تقييمًا أوليًا لمطالبة تجارية أو خدمة تحصيل في سلطنة عُمان أو عبر الحدود." : "Request an initial assessment for a commercial claim in Oman or across borders." }); }
export default async function ContactPage({ params }: { params: Promise<{ locale: Locale }> }) { const { locale } = await params; const ar = locale === "ar"; const facts = [[Phone, SITE.phoneDisplay, LINKS.phone], [Mail, SITE.email, LINKS.email], [MessageCircle, ar ? "واتساب" : "WhatsApp", LINKS.whatsapp], [MapPin, ar ? SITE.location.ar : SITE.location.en, LINKS.mapsDirections]] as const; return <><PageIntro eyebrow={ar ? "تواصل بسرية" : "CONTACT CONFIDENTIALLY"} title={ar ? "ابدأ بتقييم أولي للمطالبة" : "Start with an initial claim assessment"} description={ar ? "أرسل معلومات عامة فقط. لا ترفق مستندات أو بيانات حساسة قبل أن يوجهك الفريق إلى قناة آمنة." : "Share general information only. Do not send documents or sensitive data until the team provides a secure channel."} /><section className="py-20"><Container><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><ContactForm /><aside className="space-y-4">{facts.map(([Icon, label, href]) => <a key={label} href={href} target={href.startsWith("http") ? "_blank" : undefined} rel="noreferrer" className="flex items-center gap-4 rounded-2xl border bg-surface p-5"><span className="grid size-12 place-items-center rounded-xl bg-gold-400/10"><Icon className="size-5 text-gold-600" /></span><span>{label}</span></a>)}</aside></div></Container></section></>; }
