import type { Metadata } from "next";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import type { Locale } from "@/i18n/routing";
import { buildMetadata } from "@/lib/seo";
import { LINKS, SITE } from "@/lib/site";
import { PageIntro } from "@/components/content/PageIntro";
import { InformationGrid } from "@/components/content/PageSections";
import { ContactForm } from "@/components/sections/ContactForm";
import { MapEmbed } from "@/components/sections/MapEmbed";
import { Container } from "@/components/ui/Container";

export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }): Promise<Metadata> { const { locale } = await params; const ar = locale === "ar"; return buildMetadata({ locale, path: "/contact", title: ar ? "تواصل مع رام لتحصيل الديون" : "Contact RAM Debt Recovery", description: ar ? "اطلب تقييمًا أوليًا لمطالبة تجارية في عُمان أو عبر الحدود من فريق رام في مسقط." : "Request an initial assessment for a commercial claim in Oman or across borders from RAM in Muscat." }); }

export default async function ContactPage({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params; const ar = locale === "ar"; const facts = [[Phone, SITE.phoneDisplay, LINKS.phone], [Mail, SITE.email, LINKS.email], [MessageCircle, ar ? "محادثة واتساب" : "WhatsApp conversation", LINKS.whatsapp], [MapPin, ar ? SITE.location.ar : SITE.location.en, LINKS.mapsDirections]] as const;
  const next = ar ? [["نراجع الرسالة", "نقرأ المعلومات العامة ونحدد نوع المطالبة والخدمة الأقرب."], ["نطلب ما يلزم", "نوضح المستندات والأسئلة المطلوبة عبر قناة مناسبة."], ["نقترح الخطوة", "نشرح المسار الأولي والحدود والقرارات اللازمة."], ["نؤكد التكليف", "لا يبدأ العمل قبل اتفاق واضح على النطاق والتواصل."]] : [["We review the message", "We read the general information and identify the likely service."], ["We request what is needed", "We explain records and questions through an appropriate channel."], ["We propose a first step", "We explain the initial route, boundaries, and decisions."], ["We confirm the engagement", "Work does not start before scope and communication are agreed."]];
  return <><PageIntro eyebrow={ar ? "تواصل بسرية" : "CONTACT CONFIDENTIALLY"} title={ar ? "ابدأ بتقييم أولي للمطالبة" : "Start with an initial claim assessment"} description={ar ? "أرسل معلومات عامة فقط. لا ترفق مستندات أو بيانات حساسة قبل أن يوجهك الفريق إلى قناة مناسبة." : "Share general information only. Do not send documents or sensitive data until the team provides an appropriate channel."} /><section className="py-20"><Container><div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><ContactForm /><aside className="space-y-4"><div className="mb-6"><h2 className="text-2xl font-bold">{ar ? "قنوات التواصل المباشر" : "Direct contact channels"}</h2><p className="mt-2 text-muted">{ar ? "اختر القناة الأنسب للمعلومات العامة أو تحديد موعد." : "Choose the appropriate channel for general information or scheduling."}</p></div>{facts.map(([Icon, label, href]) => <a key={label} href={href} target={href.startsWith("http") ? "_blank" : undefined} rel="noreferrer" className="flex items-center gap-4 rounded-2xl border bg-surface p-5 transition hover:-translate-y-0.5 hover:border-gold-400/50"><span className="grid size-12 place-items-center rounded-xl bg-gold-400/10"><Icon className="size-5 text-gold-600" /></span><span className="font-semibold">{label}</span></a>)}</aside></div></Container></section><InformationGrid eyebrow={ar ? "بعد الإرسال" : "AFTER SUBMISSION"} title={ar ? "ماذا يحدث بعد أن تتواصل معنا؟" : "What happens after you contact us?"} items={next.map(([title, text]) => ({ title, text }))} tone="dark" /><InformationGrid eyebrow={ar ? "قبل إرسال الرسالة" : "BEFORE YOU WRITE"} title={ar ? "أربع معلومات تسرّع فهم الطلب" : "Four facts that speed up understanding"} items={(ar ? [["الأطراف", "من هو الدائن ومن هو المدين؟"], ["الرصيد", "المبلغ والعملة وتاريخ الاستحقاق."], ["المستندات", "ما أنواع الأدلة المتوفرة دون إرسالها الآن؟"], ["الوضع الحالي", "آخر تواصل أو اعتراض أو وعد أو دفعة."]] : [["Parties", "Who is the creditor and who is the debtor?"], ["Balance", "Value, currency, and due date."], ["Records", "Which evidence types exist without sending them yet?"], ["Current position", "Latest contact, dispute, promise, or payment."]]).map(([title, text]) => ({ title, text }))} tone="soft" /><MapEmbed /></>;
}
