import type { Metadata } from "next";
import type { Locale } from "@/i18n/routing";
import { buildMetadata } from "@/lib/seo";
import { listEntries } from "@/lib/content/repository";
import { PageIntro } from "@/components/content/PageIntro";
import { EntryCard } from "@/components/content/EntryCard";
import { InformationGrid, PageCTA, SplitNarrative } from "@/components/content/PageSections";
import { Container } from "@/components/ui/Container";

const copy = {
  ar: { title: "خبرة تحصيل تراعي طبيعة قطاعك", description: "لكل قطاع مستنداته ودورة قراره ومخاطره. نكيف التواصل والمتابعة والتقارير مع هذا السياق.", contextTitle: "القطاع يغيّر طريقة العمل، لا معايير المهنية", paragraphs: ["تبدأ قوة المطالبة من طريقة نشوء الالتزام وتوثيقه داخل القطاع: عقد تمويل، أمر شراء، عقد إيجار، موافقة خدمة أو ضمان دفع.", "نحافظ على مبادئ ثابتة في كل القطاعات: الحد الأدنى من البيانات، الاحترام، التوثيق، التناسب، والإحالة إلى المختص المرخص عند الحاجة."], points: ["فهم دورة الفاتورة والاعتماد", "تحديد الطرف المسؤول عن الدفع", "فصل الاعتراض التشغيلي عن التأخر المالي", "ضبط خصوصية البيانات الحساسة", "تكييف التقرير مع فريق الإدارة"], controlsTitle: "أساس واحد يخدم كل القطاعات", controls: [["بيانات صحيحة", "أسماء قانونية وأرصدة وتواريخ ووسائل تواصل محدثة."], ["أدلة مترابطة", "العقد والفاتورة والتسليم والمراسلات ضمن تسلسل واضح."], ["قرار في موعده", "نقطة تصعيد ومالك قرار بدل متابعة بلا نهاية."], ["تقرير قابل للعمل", "حالة وخطوة تالية ومخاطر وقرارات مطلوبة."]], ctaTitle: "لا ترى قطاعك ضمن القائمة؟", ctaText: "القائمة تعرض القطاعات الأساسية الواردة في ملف رام التعريفي وليست حصرًا. يمكن تقييم المطالبة بحسب وقائعها ومستنداتها." },
  en: { title: "Recovery expertise shaped around your sector", description: "Every sector has distinct documents, decision cycles, and risks. We adapt engagement and reporting to that context.", contextTitle: "Sector context changes the method, not professional standards", paragraphs: ["Claim strength starts with how an obligation arises and is documented in the sector: a finance contract, purchase order, lease, service authorization, or payment guarantee.", "Across sectors, our principles remain consistent: data minimization, respect, documentation, proportionality, and referral to licensed specialists where needed."], points: ["Understand invoice and approval cycles", "Identify the responsible payer", "Separate operational disputes from payment delay", "Control sensitive-data access", "Adapt reporting to management needs"], controlsTitle: "One sound foundation across sectors", controls: [["Accurate data", "Legal names, balances, dates, and current contact details."], ["Connected evidence", "Contract, invoice, delivery, and correspondence in a clear sequence."], ["Timely decisions", "Escalation point and owner rather than endless follow-up."], ["Actionable reports", "Status, next step, risk, and decisions required."]], ctaTitle: "Do not see your sector listed?", ctaText: "The list reflects the core sectors in RAM's company profile and is not exhaustive. A claim can be assessed on its own facts and records." },
} as const;

export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }): Promise<Metadata> { const { locale } = await params; return buildMetadata({ locale, path: "/industries", title: `${copy[locale].title} | RAM`, description: copy[locale].description }); }

export default async function IndustriesPage({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params; const t = copy[locale]; const items = await listEntries({ type: "industry", locale });
  return <><PageIntro eyebrow={locale === "ar" ? "القطاعات" : "INDUSTRIES"} title={t.title} description={t.description} /><section className="py-20"><Container><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{items.map((entry) => <EntryCard key={entry.id} entry={entry} />)}</div></Container></section><SplitNarrative eyebrow={locale === "ar" ? "فهم السياق" : "CONTEXT MATTERS"} title={t.contextTitle} paragraphs={[...t.paragraphs]} points={[...t.points]} /><InformationGrid eyebrow={locale === "ar" ? "عبر جميع القطاعات" : "ACROSS EVERY SECTOR"} title={t.controlsTitle} items={t.controls.map(([title, text]) => ({ title, text }))} tone="soft" /><PageCTA title={t.ctaTitle} text={t.ctaText} action={locale === "ar" ? "ناقش مطالبتك" : "Discuss your claim"} secondary={locale === "ar" ? "استكشف الخدمات" : "Explore services"} secondaryHref="/services" /></>;
}
