import type { Locale } from "@/i18n/routing";
import { PageIntro } from "@/components/content/PageIntro";
import { InformationGrid, PageCTA, SplitNarrative } from "@/components/content/PageSections";

const copy = {
  ar: {
    title: "الامتثال والسرية في كل مرحلة", description: "مبادئ تشغيلية تحكم استلام المعلومات والتواصل والتوثيق والتصعيد.",
    ethicsTitle: "النزاهة في الممارسة، لا في الشعارات فقط", ethics: ["يوضح ملف رام التعريفي أن العمليات تتماشى مع قوانين سلطنة عُمان وإرشادات التحصيل الدولية المعترف بها.", "نتواصل مع المدينين باحترام ومهنية، دون مضايقة أو ضغط غير مشروع، ونركز على حلول عادلة وموثقة وقابلة للتنفيذ."],
    points: ["لا تهديد أو إحراج أو كشف للدين أمام الغير", "لا تقديم استشارة قانونية من غير مختص مرخص", "لا مشاركة بيانات بلا أساس أو موافقة مناسبة", "لا وعد بنتيجة أو مدة لا يمكن ضمانها", "توثيق الوقائع والقرارات والتطورات"],
    pillarsTitle: "ضوابط تحكم دورة الملف", pillars: [["الحد الأدنى من البيانات", "نطلب فقط ما يلزم للتقييم أو الخطوة المعتمدة."], ["الوصول حسب الحاجة", "تصل المعلومات إلى الأشخاص المخولين المرتبطين بالمهمة."], ["قنوات مناسبة", "لا تُطلب المستندات الحساسة عبر النماذج أو القنوات العامة."], ["إفصاح منضبط", "لا تُشارك المعلومات مع طرف ثالث دون أساس قانوني أو موافقة مناسبة."], ["تواصل محترم", "رسائل مهنية تبتعد عن التهديد والضغط غير المشروع."], ["إحالة مرخصة", "المشورة والتمثيل القانونيان لدى محامين مخولين."], ["سجل قابل للمراجعة", "توثيق الاتصال والعرض والاعتراض والقرار والنتيجة."], ["إغلاق منظم", "تحديد ما يُحفظ أو يُعاد أو يُحذف وفق الالتزامات والغرض."]],
    lifecycleTitle: "كيف تتحرك البيانات داخل الملف؟", lifecycle: [["الاستلام", "معلومات عامة أولًا ثم قناة مناسبة للمستندات."], ["المراجعة", "حصر الوصول بمن يقيّم أو ينفذ المهمة."], ["الاستخدام", "توظيف البيانات للغرض المتفق عليه فقط."], ["الإغلاق", "حفظ أو إعادة أو إزالة المعلومات بحسب المتطلبات."]],
  },
  en: {
    title: "Compliance and confidentiality at every stage", description: "Operating principles governing information intake, engagement, documentation, and escalation.",
    ethicsTitle: "Integrity in practice, not just in statements", ethics: ["RAM's company profile states that operations align with the laws of the Sultanate of Oman and recognized international debt-collection guidance.", "We engage debtors respectfully and professionally, without harassment or unlawful pressure, focusing on fair, documented, solution-oriented communication."],
    points: ["No threats, embarrassment, or disclosure to unrelated people", "No legal advice from anyone who is not appropriately licensed", "No data sharing without a legal basis or suitable consent", "No promises of outcomes or timing that cannot be guaranteed", "Document facts, decisions, and developments"],
    pillarsTitle: "Controls across the matter lifecycle", pillars: [["Data minimization", "Request only what the assessment or approved step requires."], ["Need-to-know access", "Information reaches only authorized people connected to the task."], ["Appropriate channels", "Sensitive records are not requested through public forms or channels."], ["Controlled disclosure", "Information is not shared without legal basis or suitable approval."], ["Respectful engagement", "Professional messages avoid threats and unlawful pressure."], ["Licensed referral", "Legal advice and representation remain with authorized lawyers."], ["Reviewable record", "Contacts, offers, disputes, decisions, and outcomes are recorded."], ["Structured closure", "Retention, return, or deletion follows purpose and requirements."]],
    lifecycleTitle: "How does data move through a matter?", lifecycle: [["Intake", "General information first, then an appropriate document channel."], ["Review", "Access is limited to those assessing or performing the task."], ["Use", "Information is used only for the agreed purpose."], ["Closure", "Records are retained, returned, or removed under applicable requirements."]],
  },
} as const;

export default async function Compliance({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params; const t = copy[locale]; const ar = locale === "ar";
  return <><PageIntro eyebrow={ar ? "الثقة والحوكمة" : "TRUST & GOVERNANCE"} title={t.title} description={t.description} /><SplitNarrative eyebrow={ar ? "النزاهة" : "INTEGRITY"} title={t.ethicsTitle} paragraphs={[...t.ethics]} points={[...t.points]} /><InformationGrid eyebrow={ar ? "ثمانية مبادئ" : "EIGHT PRINCIPLES"} title={t.pillarsTitle} items={t.pillars.map(([title, text]) => ({ title, text }))} tone="dark" /><InformationGrid eyebrow={ar ? "دورة المعلومات" : "INFORMATION LIFECYCLE"} title={t.lifecycleTitle} items={t.lifecycle.map(([title, text]) => ({ title, text }))} tone="soft" /><PageCTA title={ar ? "شارك الحد الأدنى أولًا" : "Share the minimum first"} text={ar ? "استخدم نموذج التواصل للمعلومات العامة فقط. بعد المراجعة الأولية يوجهك الفريق إلى القناة المناسبة لأي مستندات حساسة." : "Use the contact form for general information only. After initial review, the team will direct you to an appropriate channel for sensitive records."} action={ar ? "تواصل بسرية" : "Contact confidentially"} secondary={ar ? "اقرأ سياسة الخصوصية" : "Read the privacy policy"} secondaryHref="/privacy" /></>;
}
