import { notFound } from "next/navigation";
import { addLeadNote, updateLeadStatus } from "@/app/admin/(protected)/leads/actions";
import { requirePermission } from "@/lib/auth/session";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export default async function LeadDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePermission("leads:read"); const { id } = await params; const supabase = await createSupabaseServerClient();
  const [{ data: lead }, { data: notes }] = await Promise.all([supabase.from("leads").select("*").eq("id", id).maybeSingle(), supabase.from("lead_notes").select("*").eq("lead_id", id).order("created_at", { ascending: false })]);
  if (!lead) notFound();
  return <><h1 className="text-3xl font-bold">{lead.full_name}</h1><p className="mt-2 text-slate-500">Lead ID: <span dir="ltr">{lead.id}</span></p><div className="mt-8 grid gap-6 xl:grid-cols-[1fr_360px]"><section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">تفاصيل الطلب</h2><dl className="mt-6 grid gap-5 sm:grid-cols-2">{[["الشركة", lead.company], ["البريد", lead.email], ["الهاتف", lead.phone], ["الخدمة", lead.service_interest], ["التواصل المفضل", lead.preferred_contact], ["المصدر", lead.source]].map(([key, value]) => <div key={key}><dt className="text-xs text-slate-500">{key}</dt><dd className="mt-1 font-medium">{value || "—"}</dd></div>)}</dl><h3 className="mt-8 font-bold">الرسالة</h3><p className="mt-2 whitespace-pre-wrap rounded-xl bg-slate-50 p-4">{lead.message}</p></section><aside className="space-y-6"><form action={updateLeadStatus} className="rounded-2xl border bg-white p-5"><input type="hidden" name="id" value={lead.id} /><label className="font-bold">الحالة<select name="status" defaultValue={lead.status} className="mt-3 w-full rounded-xl border p-3">{["new", "contacted", "qualified", "closed", "spam"].map((s) => <option key={s}>{s}</option>)}</select></label><button className="mt-3 w-full rounded-xl bg-navy-800 p-3 font-bold text-white">حفظ الحالة</button></form><form action={addLeadNote} className="rounded-2xl border bg-white p-5"><input type="hidden" name="leadId" value={lead.id} /><label className="font-bold">ملاحظة داخلية<textarea required name="body" rows={4} maxLength={5000} className="mt-3 w-full rounded-xl border p-3" /></label><button className="mt-3 rounded-xl border px-5 py-2.5 font-bold">إضافة ملاحظة</button></form></aside></div><section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">سجل الملاحظات</h2><div className="mt-5 space-y-3">{notes?.map((note) => <article key={note.id} className="rounded-xl bg-slate-50 p-4"><p>{note.body}</p><time className="mt-2 block text-xs text-slate-500">{new Date(note.created_at).toLocaleString("ar-OM")}</time></article>)}{!notes?.length && <p className="text-slate-500">لا توجد ملاحظات بعد.</p>}</div></section></>;
}
