import type { Metadata } from "next";
import { Building2, Globe2, ShieldCheck } from "lucide-react";
import type { Locale } from "@/i18n/routing";
import { buildMetadata } from "@/lib/seo";
import { PageIntro } from "@/components/content/PageIntro";
import { Container } from "@/components/ui/Container";

export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }): Promise<Metadata> { const { locale } = await params; const ar = locale === "ar"; return buildMetadata({ locale, path: "/about", title: ar ? "عن رام للتنمية المستدامة" : "About RAM Sustainable Development", description: ar ? "تعرف على نشأة قسم تحصيل الديون في رام وخبرته الإقليمية ومنهجه المهني." : "Learn about RAM's debt collection practice, regional experience, and professional approach." }); }
export default async function AboutPage({ params }: { params: Promise<{ locale: Locale }> }) { const { locale } = await params; const ar = locale === "ar"; return <><PageIntro eyebrow={ar ? "عن رام" : "ABOUT RAM"} title={ar ? "خبرة إقليمية، وحضور محلي، ومنهج واضح" : "Regional experience, local presence, and a clear method"} description={ar ? "تأسس قسم تحصيل الديون في رام بسلطنة عُمان عام 2018، مستندًا إلى خبرة عمل في المجال منذ 2012 عبر الخليج وتركيا." : "RAM's debt collection department was established in Oman in 2018, building on experience in the field since 2012 across the Gulf and Türkiye."} /><section className="py-20"><Container><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-bold text-gold-700">2012 → 2018 → {new Date().getFullYear()}</p><h2 className="mt-4 text-4xl font-bold">{ar ? "من الخبرة إلى منظومة استرداد متكاملة" : "From experience to an integrated recovery practice"}</h2><div className="mt-6 space-y-5 text-lg text-muted"><p>{ar ? "تجمع رام بين التقييم العملي للمطالبة، والتواصل المهني، والتفاوض، والمتابعة الميدانية، والتنسيق القانوني عند الحاجة." : "RAM brings together practical claim assessment, professional communication, negotiation, field follow-up, and legal coordination when needed."}</p><p>{ar ? "نخدم الشركات والمؤسسات المالية والمستثمرين والجهات المهنية بملفات داخل سلطنة عُمان وعبر الحدود." : "We serve companies, financial institutions, investors, and professional firms with matters in Oman and across borders."}</p></div></div><div className="grid gap-4">{[[Building2, ar ? "مقرنا مسقط" : "Based in Muscat"], [Globe2, ar ? "عمل إقليمي ودولي" : "Regional and international scope"], [ShieldCheck, ar ? "السرية والنزاهة" : "Confidentiality and integrity"]].map(([Icon, label]) => { const C = Icon as typeof Building2; return <div key={String(label)} className="flex items-center gap-4 rounded-2xl border bg-surface p-5"><span className="grid size-12 place-items-center rounded-xl bg-gold-400/10"><C className="size-6 text-gold-600" /></span><h3 className="text-xl font-bold">{String(label)}</h3></div>; })}</div></div></Container></section></>; }
